#pragma once

// Externals
#include <vulkan/vulkan_raii.hpp>

// STL
#include <atomic>
#include <fstream>
#include <functional>
#include <iostream>
#include <mutex>
#include <source_location>
#include <string>
#include <string_view>
#include <unordered_map>

namespace gcep
{
    //  Log level — strongly typed, bitmask-capable
    enum class LogLevel : uint32_t
    {
        eNone    = 0,
        eCommon  = 1 << 0,
        eWarn    = 1 << 1,
        eError   = 1 << 2,
        eVerbose = 1 << 3,
        eAll     = eCommon | eWarn | eError | eVerbose
    };

    inline LogLevel operator|(LogLevel a, LogLevel b)
    {
        return static_cast<LogLevel>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
    }
    inline LogLevel operator&(LogLevel a, LogLevel b)
    {
        return static_cast<LogLevel>(static_cast<uint32_t>(a) & static_cast<uint32_t>(b));
    }
    inline bool hasFlag(LogLevel mask, LogLevel flag)
    {
        return (mask & flag) != LogLevel::eNone;
    }

    //  Log channel — named, independent file + level per channel
    struct LogChannel
    {
        std::string   name;
        std::ofstream file;
        LogLevel      levelMask { LogLevel::eAll };
        bool          mirrorToConsole { true };

        // Non-copyable, movable
        LogChannel() = default;
        LogChannel(const LogChannel&) = delete;
        LogChannel& operator=(const LogChannel&) = delete;
        LogChannel(LogChannel&&) = default;
        LogChannel& operator=(LogChannel&&) = default;
    };

    //  Log — thread-safe, multi-channel logger with crash reporting
    class Log
    {
    public:
        // Initialisation

        /// Must be called once before any logging.
        /// @param appName        Human-readable application name embedded in reports.
        /// @param crashLogPath   File path for crash reports generated by signal/exception handlers.
        static void initialize(std::string appName,
                               std::string crashLogPath);

        /// Must be called once .
        /// @param physicalDevice Optional Vulkan device pointer for richer crash reports.
        static void setVulkanDevice(vk::raii::PhysicalDevice* physicalDevice);

        // Channel management

        /// Open (or reopen) a named channel backed by a log file.
        /// Returns false if the file cannot be opened.
        static bool openChannel(std::string_view   channelName,
                                const std::string& filePath,
                                LogLevel           levelMask       = LogLevel::eAll,
                                bool               mirrorToConsole = true);

        /// Change the active level mask of an existing channel at runtime.
        static void setChannelLevel(std::string_view channelName, LogLevel levelMask);

        /// Close a channel and flush/release its file.
        static void closeChannel(std::string_view channelName);

        // Core logging API

        /// Write a message to a named channel if the channel's level mask permits it.
        static void log(std::string_view            channelName,
                        LogLevel                    level,
                        std::string_view            message,
                        const std::source_location& location = std::source_location::current());

        /// Convenience overloads that target the "default" channel.
        static void info   (std::string_view msg, const std::source_location& loc = std::source_location::current());
        static void warn   (std::string_view msg, const std::source_location& loc = std::source_location::current());
        static void error  (std::string_view msg, const std::source_location& loc = std::source_location::current());
        static void verbose(std::string_view msg, const std::source_location& loc = std::source_location::current());

        // Flush

        /// Flush all open channels to disk immediately.
        static void flushAll();

        // Crash reporting

        /// Write a structured crash report for a C++ exception.
        static void handleException(const std::exception& e);

        /// Write a structured crash report for an OS signal (SIGSEGV, SIGILL, ...).
        /// Registered automatically by initialize(); may also be set manually.
        static void signalHandler(int signalNum);

        // System / Vulkan info (also exposed for manual calls)
        static void logSystemInfo(std::ofstream& out);
        static void logVulkanInfo(std::ofstream& out, vk::raii::PhysicalDevice* dev);

        // Helpers

        /// Returns a human-readable label for a log level.
        static constexpr std::string_view levelToString(LogLevel level) noexcept;

    private:
        // Internal write - assumes caller already holds s_mutex.
        static void writeEntry(LogChannel&                 channel,
                               LogLevel                    level,
                               std::string_view            message,
                               const std::source_location& location);

        static std::string buildTimeHeader();

        // State
        static std::mutex                                    s_mutex;
        static std::unordered_map<std::string, LogChannel>   s_channels;
        static std::string                                   s_appName;
        static std::string                                   s_crashLogPath;
        static std::atomic<vk::raii::PhysicalDevice*>        s_physicalDevice;
        static std::atomic<bool>                             s_initialized;
    };

    //  Convenience macros  (wrap source_location automatically)=
    #define GCEP_LOG(channel, level, msg)  ::gcep::Log::log(channel, level, msg)
    #define GCEP_INFO(msg)                 ::gcep::Log::info(msg)
    #define GCEP_WARN(msg)                 ::gcep::Log::warn(msg)
    #define GCEP_ERROR(msg)                ::gcep::Log::error(msg)
    #define GCEP_VERBOSE(msg)              ::gcep::Log::verbose(msg)

    //  Inline constexpr helpers
    constexpr std::string_view Log::levelToString(LogLevel level) noexcept
    {
        switch (level)
        {
            case LogLevel::eCommon:  return "INFO";
            case LogLevel::eWarn:    return "WARN";
            case LogLevel::eError:   return "ERROR";
            case LogLevel::eVerbose: return "VERBOSE";
            default:                 return "UNKNOWN";
        }
    }
} // namespace gcep
