// SCRIPT_NAME.cpp
// Generated by GCEngine script system.
// Rename this file and the struct below to something meaningful.
// This file will be hot-reloaded automatically when saved.

#include "script_api.hpp"

struct SCRIPT_NAME
{
    // Per-instance data
    // Fields here persist across frames for the lifetime of this component.
    // They are reset every time the script is hot-reloaded.

    float timer = 0.f;

    // Lifecycle

    void onStart(const ScriptContext* ctx)
    {
        // Called once when the simulation starts, or after a hot-reload.
        // ctx->entityId is the ECS ID of the entity this script is attached to.
    }

    void onUpdate(const ScriptContext* ctx)
    {
        // Called every frame while the simulation is playing.
        timer += ctx->deltaTime;
    }

    void onEnd(const ScriptContext* ctx)
    {
        // Called when the simulation stops, or just before a hot-reload.
    }
};

// Do not delete this line.
DECLARE_SCRIPT(SCRIPT_NAME)
