name: C++ Vulkan CI/CD

on:
  push:
    tags:
      - 'release*'

jobs:
  build-test:
    name: Build, Lint, Test on ${{ matrix.os }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
        compiler: [clang]

    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential clang-tidy clang-format git libwayland-dev wayland-protocols libxkbcommon-dev libxinerama-dev libxcursor-dev libxi-dev libx11-dev libegl1-mesa-dev libgl1-mesa-dev xorg-dev pkg-config


      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install llvm

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Add LLVM to PATH
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
          else
            echo "/usr/bin" >> $GITHUB_PATH
          fi

      - name: Add Vulkan dynamic libs to 'LD_LIBRARY_PATH' (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "LD_LIBRARY_PATH=$VULKAN_SDK/lib:$VULKAN_SDK/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/Testing/Temporary

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/
